Label: "Test"
Characters:
  - Base:
      Name: Ganyu
      Level: 90
      Element: "cryo"
      BaseHP: 9797
      BaseAtk: 335
      BaseDef: 630
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 0
    AscensionBonus:
      CD: 0.384
    TalentLevel:
      attack: 10
      skill: 6
      burst: 6
    Weapon:
      WeaponName: "Prototype Crescent"
      WeaponRefinement: 4
      WeaponBaseAtk: 510
    WeaponSecondaryStat:
      ATK%: 0.413
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Blizzard Strayer"
        Main:
          HP: 4780
        Sub:
          EM: 21
          ATK: 47
          CD: 0.179
          DEF: 19
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Blizzard Strayer"
        Main:
          ATK: 311
        Sub:
          CD: 0.062
          EM: 35
          ATK%: 0.157
          CR: 0.07
      Sands:
        Level: 20
        Type: "Sands"
        Set: "Blizzard Strayer"
        Main:
          ATK%: 0.466
        Sub:
          ATK: 31
          CD: 0.225
          HP%: 0.047
          ER: 0.168
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Crimson Witch of Flames"
        Main:
          Cryo%: 0.466
        Sub:
          CD: 0.07
          CR: 0.093
          HP: 717
          DEF: 16
      Circlet:
        Level: 20
        Type: "Circlet"
        Set: "Blizzard Strayer"
        Main:
          CD: 0.622
        Sub:
          CR: 0.097
          DEF: 21
          ATK%: 0.14
          DEF%: 0.066
Enemy:
  Level: 88
  Resist:
    pyro: 0.5
    dendro: 0.1
    hydro: 0.1
    cryo: 0.1
    electro: 0.1
    geo: 0.1
    anemo: 0.1
    physical: -0.2
InitialActive: "Ganyu"
Rotation:
  - CharacterName: "Ganyu"
    Action: "skill"
  - CharacterName: "Ganyu"
    Action: "burst"
  - CharacterName: "Ganyu"
    Action: "aimed"
