Label: "Test"
Characters:
  - Name: Fischl
    Level: 70
    Element: "electro"
    BaseHP: 7508
    BaseAtk: 200
    BaseDef: 485
    BaseCR: 0.05
    BaseCD: 0.50
    Constellation: 4
    AscensionBonus:
      ATK%: 0.18
    TalentLevel:
      attack: 4
      skill: 6
      burst: 2
    WeaponName: "Favonius Warbow"
    WeaponRefinement: 5
    WeaponBaseAtk: 401
    WeaponSecondaryStat:
      ER%: 0.559
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Wanderer's Troupe"
        MainStat:
          Type: "HP"
          Value: 4780
        Substat:
          - Type: "CD"
            Value: 0.109
          - Type: "ATK%"
            Value: 0.087
          - Type: "CR"
            Value: 0.109
          - Type: "ATK"
            Value: 33
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Wanderer's Troupe"
        MainStat:
          Type: "ATK"
          Value: 311
        Substat:
          - Type: "CD"
            Value: 0.172
          - Type: "ER"
            Value: 0.091
          - Type: "ATK%"
            Value: 0.058
          - Type: "CR"
            Value: 0.062
      Sands:
        Level: 16
        Type: "Sands"
        Set: "Gladiator's Finale"
        MainStat:
          Type: "ATK%"
          Value: 0.387
        Substat:
          - Type: "EM"
            Value: 35
          - Type: "CR"
            Value: 0.039
          - Type: "ATK"
            Value: 49
          - Type: "HP"
            Value: 508
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Gladiator's Finale"
        MainStat:
          Type: "Electro%"
          Value: 0.466
        Substat:
          - Type: "ATK%"
            Value: 0.105
          - Type: "EM"
            Value: 61
          - Type: "CR"
            Value: 0.027
          - Type: "ER"
            Value: 0.11
      Circlet:
        Level: 16
        Type: "Circlet"
        Set: "Blizzard Strayer"
        MainStat:
          Type: "CR"
          Value: 0.258
        Substat:
          - Type: "ATK%"
            Value: 0.041
          - Type: "ATK"
            Value: 53
          - Type: "ER%"
            Value: 0.058
          - Type: "HP"
            Value: 568
Enemy: #blazing axe mitachurl
  Level: 88
  Resist:
    pyro: 0.1
    dendro: 0.1
    hydro: 0.1
    cryo: 0.1
    electro: 0.1
    geo: 0.1
    anemo: 0.1
    physical: 0.3
InitialActive: "Xiangling"
Rotation:
  - CharacterName: "Xiangling"
    Action: "skill"
  - CharacterName: "Xiangling"
    Action: "burst"
  - CharacterName: "Ganyu"
    Action: "skill"
  - CharacterName: "Ganyu"
    Action: "burst"
  - CharacterName: "Ganyu"
    Action: "charge"
