Label: "Test"
Characters:
  - Base:
      Name: Eula
      Level: 90
      Element: "cryo"
      BaseHP: 13226
      BaseAtk: 342
      BaseDef: 751
      BaseCR: 0.05
      BaseCD: 0.50
    Constellation: 0
    AscensionBonus:
      CD: 0.384
    TalentLevel:
      attack: 8
      skill: 6
      burst: 9
    Weapon:
      WeaponName: "Skyward Pride"
      WeaponRefinement: 1
      WeaponBaseAtk: 674
    WeaponSecondaryStat:
      ER: 0.368
    Artifacts:
      Flower:
        Level: 20
        Set: "Pale Flame"
        Main:
          HP: 4780
        Sub:
          CR: .429
          CD: 0.726
          ATK%: 0.20
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Pale Flame"
        Main:
          ATK: 311
      Sands:
        Level: 20
        Type: "Sands"
        Set: "Pale Flame"
        Main:
          ATK%: 0.466
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Pale Flame"
        Main:
          Phys%: 0.466
      Circlet:
        Level: 20
        Type: "Circlet"
        Set: "Pale Flame"
        Main:
          CR: 0.311
  - Base:
      Name: Fischl
      Level: 70
      Element: "electro"
      BaseHP: 7508
      BaseAtk: 200
      BaseDef: 485
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 4
    AscensionBonus:
      ATK%: 0.18
    TalentLevel:
      attack: 4
      skill: 6
      burst: 2
    Weapon:
      WeaponName: "Favonius Warbow"
      WeaponRefinement: 5
      WeaponBaseAtk: 401
    WeaponSecondaryStat:
      ER%: 0.559
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Wanderer's Troupe"
        Main:
          HP: 4780
        Sub:
          CD: 0.109
          ATK%: 0.087
          CR: 0.109
          ATK: 33
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Wanderer's Troupe"
        Main:
          ATK: 311
        Sub:
          CD: 0.172
          ER: 0.091
          ATK%: 0.058
          CR: 0.062
      Sands:
        Level: 16
        Type: "Sands"
        Set: "Gladiator's Finale"
        Main:
          ATK%: 0.387
        Sub:
          EM: 35
          CR: 0.039
          ATK: 49
          HP: 508
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Gladiator's Finale"
        Main:
          Electro%: 0.466
        Sub:
          ATK%: 0.105
          EM: 61
          CR: 0.027
          ER: 0.11
      Circlet:
        Level: 16
        Type: "Circlet"
        Set: "Blizzard Strayer"
        Main:
          CR: 0.258
        Sub:
          ATK%: 0.041
          ATK: 53
          ER%: 0.058
          HP: 568
  - Base:
      Name: Xingqiu
      Level: 70
      Element: "hydro"
      BaseHP: 8352
      BaseAtk: 165
      BaseDef: 619
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 6
    AscensionBonus:
      ATK%: 0.18
    TalentLevel:
      attack: 1
      skill: 6
      burst: 6
    Weapon:
      WeaponName: "Sacrificial Sword"
      WeaponRefinement: 3
      WeaponBaseAtk: 401
    WeaponSecondaryStat:
      ER: 0.559
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Gladiator's Finale"
        Main:
          HP: 4780
        Sub:
          ATK: 45
          DEF: 21
          ATK%: 0.105
          CD: 0.194
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Gladiator's Finale"
        Main:
          ATK: 311
        Sub:
          CD: 0.218
          DEF: 19
          ATK%: 0.117
          EM: 40
      Sands:
        Level: 20
        Type: "Sands"
        Set: "Thundersoother"
        Main:
          ATK%: 0.466
        Sub:
          CR: 0.066
          HP: 209
          ER: 0.175
          DEF%: 0.109
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Maiden Beloved"
        Main:
          Hydro%: 0.466
        Sub:
          CD: 0.124
          HP%: 0.047
          ATK%: 0.146
          ATK: 31
      Circlet:
        Level: 16
        Type: "Circlet"
        Set: "Bloodstained Chivalry"
        Main:
          CR: 0.258
        Sub:
          HP%: 0.093
          ATK: 31
          DEF: 42
          CD: 0.14
  - Base:
      Name: Diona
      Level: 70
      Element: "cryo"
      BaseHP: 8352
      BaseAtk: 165
      BaseDef: 619
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 6
    TalentLevel:
      attack: 1
      skill: 6
      burst: 6
    Weapon:
      WeaponName: "Favonius Warbow"
      WeaponRefinement: 3
      WeaponBaseAtk: 401
    WeaponSecondaryStat:
      ER: 0.559
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Gladiator's Finale"
        Main:
          HP: 4780
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Gladiator's Finale"
        Main:
          ATK: 311
      Sands:
        Level: 20
        Type: "Sands"
        Set: "Thundersoother"
        Main:
          ATK%: 0.466
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Maiden Beloved"
        Main:
          Hydro%: 0.466
      Circlet:
        Level: 16
        Type: "Circlet"
        Set: "Bloodstained Chivalry"
        Main:
          CR: 0.258
Enemy:
  Level: 88
  Resist:
    pyro: 0.1
    dendro: 0.1
    hydro: 0.1
    cryo: 0.1
    electro: 0.1
    geo: 0.1
    anemo: 0.1
    physical: 0.1
InitialActive: "Eula"
Rotation:
  - CharacterName: "Xingqiu"
    Action: "burst"
  - CharacterName: "Xingqiu"
    Action: "skill"
  - CharacterName: "Fischl"
    Action: "burst"
    ConditionType: "status"
    ConditionTarget: "Fischl-Oz"
    ConditionBool: false
  - CharacterName: "Fischl"
    Action: "skill"
    ConditionType: "status"
    ConditionTarget: "Fischl-Oz"
  #   ConditionBool: false
  # - CharacterName: "Xiangling"
  #   Action: "burst"
  # - CharacterName: "Xiangling"
  #   Action: "skill"
  - CharacterName: "Eula"
    Action: "burst"
    SwapLock: 480
  - CharacterName: "Eula"
    Action: "skill"
    Params:
      Hold: 1
    ConditionType: "tags"
    ConditionTarget: "Grimheart"
    ConditionInt: 2
  - CharacterName: "Eula"
    Action: "skill"
  - CharacterName: "Eula"
    Action: "attack"
  - CharacterName: "Fischl"
    Action: "attack"
  - CharacterName: "Xingqiu"
    Action: "attack"
